# Generated by Django 4.0.5 on 2022-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='tracking_code',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
