# Generated by Django 4.0.5 on 2022-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_date_orderdetail_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
