# Generated by Django 4.0.5 on 2022-06-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderdetail_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='tracking_code',
        ),
    ]
